# Generated by Django 4.1.3 on 2022-11-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BudgetMonth", models.IntegerField(choices=[(1, "Jan"), (2, "Feb")])),
                ("Amount", models.FloatField()),
            ],
            options={"db_table": "Budget",},
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IconImage",
                    models.FileField(
                        default="default_icon.png", upload_to="IconImages/"
                    ),
                ),
                ("Category", models.CharField(max_length=50)),
            ],
            options={"db_table": "ExpenseCategory",},
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
                ("IsActive", models.BooleanField(default=False)),
            ],
            options={"db_table": "master",},
        ),
        migrations.CreateModel(
            name="MemberCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=25)),
            ],
            options={"db_table": "MemberCategory",},
        ),
        migrations.CreateModel(
            name="MemberList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MemberCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.membercategory",
                    ),
                ),
            ],
            options={"db_table": "MemberList",},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProfileImage",
                    models.FileField(default="default_icon.png", upload_to="profiles/"),
                ),
                ("UserName", models.CharField(blank=True, default="", max_length=25)),
                ("FullName", models.CharField(blank=True, default="", max_length=25)),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "male"), ("f", "female")],
                        default="",
                        max_length=5,
                    ),
                ),
                ("BirthDate", models.DateField()),
                ("Address", models.TextField(blank=True, default="", max_length=100)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.master",
                    ),
                ),
            ],
            options={"db_table": "userprofile",},
        ),
        migrations.CreateModel(
            name="SharedExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Amount", models.FloatField()),
                ("Date", models.DateField()),
                ("Description", models.TextField(max_length=100)),
                (
                    "ExpenseReciept",
                    models.FileField(
                        default="default.png", upload_to="ExpenseReciept/"
                    ),
                ),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.master",
                    ),
                ),
                (
                    "MemberList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.memberlist",
                    ),
                ),
            ],
            options={"db_table": "SharedExpense",},
        ),
        migrations.AddField(
            model_name="memberlist",
            name="UserProfile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgetApp.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Amount", models.FloatField()),
                ("Date", models.DateField()),
                ("Description", models.TextField(max_length=100)),
                (
                    "Budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.budget",
                    ),
                ),
                (
                    "ExpenseCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.expensecategory",
                    ),
                ),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budgetApp.userprofile",
                    ),
                ),
            ],
            options={"db_table": "Expense",},
        ),
        migrations.AddField(
            model_name="budget",
            name="UserProfile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="budgetApp.userprofile"
            ),
        ),
    ]
