# Generated by Django 4.1.3 on 2022-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetApp", "0003_alter_userprofile_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="CreatedOn",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="budget",
            name="BudgetMonth",
            field=models.IntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ]
            ),
        ),
    ]
